{{- if and .Values.proxyservice.enabled (not .Values.standalone.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "milvus-ha.proxyservice.fullname" . }}
  labels:
{{ include "milvus-ha.labels" . | indent 4 }}
    component: "proxyservice"
spec:
  replicas: {{ .Values.proxyservice.replicas }}
  selector:
    matchLabels:
{{ include "milvus-ha.matchLabels" . | indent 6 }}
      component: "proxyservice"
  template:
    metadata:
      labels:
{{ include "milvus-ha.matchLabels" . | indent 8 }}
        component: "proxyservice"
    spec:
      {{- if .Values.image.all.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.all.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: proxyservice
        image: "{{ .Values.image.all.repository }}:{{ .Values.image.all.tag }}"
        imagePullPolicy: {{ .Values.image.all.pullPolicy }}
        args: [ "/milvus-distributed/bin/proxyservice" ]
        env:
        {{- if .Values.proxyservice.extraEnv }}
          {{- toYaml .Values.proxyservice.extraEnv | nindent 10 }}
        {{- end }}
        ports:
          - name: proxyservice
            containerPort: 21122
            protocol: TCP
        resources:
          {{- toYaml .Values.proxyservice.resources | nindent 10 }}
        volumeMounts:
        - name: milvus-ha-config
          mountPath: /milvus-distributed/configs/milvus.yaml
          subPath: milvus.yaml
          readOnly: true
        - name: milvus-logs-disk
          mountPath: {{ .Values.logsPersistence.mountPath | quote }}
          subPath: {{ .Values.logsPersistence.persistentVolumeClaim.subPath | default "" }}

      {{- with .Values.proxyservice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxyservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.proxyservice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
      - name: milvus-ha-config
        configMap:
          name: {{ template "milvus-ha.fullname" . }}
      - name: milvus-logs-disk
        {{- if .Values.logsPersistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.logsPersistence.persistentVolumeClaim.existingClaim | default (printf "%s-logs" (include "milvus-ha.fullname" . | trunc 58)) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
